- name: my Sql Setup
  hosts: all
  become: yes
  tasks:
    - name: Disable Mysql version
      ansible.builtin.shell: dnf module disable mysql -y
    - name: copy mysql file
      ansible.builtin.file:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo
    - name: Install mysql server
      ansible.builtin.dnf:
        name: mysql-community-server
        state: present
    - name: start mysql server
      ansible.builtin.systemd:
        name: mysqld
        state: restarted
        enabled: yes
    - name: set mysql password
      ansible.builtin.shell: mysql_secure_installation --set--root-pass ${{MYSQL_ROOT_PASSWORD}}


