- name: Installing nginx
  ansible.builtin.dnf:
    name: nginx
    state: present
#copy expense.conf file to /etc
- name: Copy Expense Config File
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf
#import common role app  pre-req to frontend
- name: import common role-App pre-req
  ansible.builtin.import_role:
    name: common
    tasks_from: app-preq
  vars:
    app_dir: /app
    component: backend

#Restart Nginx service
- name: Start Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
